### PR TITLE
fix for gulp 4 (deal with outdated vinyl)

### PR DESCRIPTION
**Pull request by ruidfigueiredo**
Hey, the newer version of vinyl that gulp 4 uses does not have the pipe method, and that causes issue #14 

By using `file.isBuffer` we can check if the contents are a buffer and use stream's Readable.from to convert it to a readable stream.

### CODE REVIEW

**Comment by ruidfigueiredo** [comment]
I've also bumped the major version as this might be a breaking change for users of gulp v3

Sorry about the formatting change (I didn't notice I had prettier on)

**Comment by albertorestifo** [comment]
Thank you for your contribution! 🙏 

I don't use this package anymore, so can you confirm you tested the changes and it works as expected?

**Comment by ruidfigueiredo** [comment]
I did try it. I had to upgrade a big gulpfile from v3 to v4 and this was the only thing that wasn't smooth. In the end it was because the pipe function had been deprecated (that's the reason for #14 )

I've been running a local copy of this plugin with these changes

**Comment by albertorestifo** [comment]
Thanks again for your contribution, version 3.0.0 released to NPM

**Pull request merged**
